Javascript best practice
ridwanediallo/code-review pull request #1
Opened 2022-03-01 08:05 UTC by ridwanediallo

Hey Max, here is my project. Could you review it?

2022-03-01 23:19 UTC, i-max-xi reviewed
Great work 👍 on the project.
Commendation on clean and well organized code.
Just a few changes to implement

2022-03-01 23:34 UTC, i-max-xi requested changes

2022-03-01 23:34 UTC, i-max-xi commented on src/index.html
> +        <div class="title-holder">
This implementation in HTML is what is usually termed, a "div soup".
It means wrapping content in too many divs than necessary.

Please refer to the resource below for additional info on "div soup" 
[Click here](https://www.chillybin.com.sg/would-you-like-another-bowl-of-div-soup/) to access resource

2022-03-02 09:03 UTC, ridwanediallo commented on src/index.html
> +        <div class="title-holder">
Great! Thank you for letting me know about it.

2022-03-05 07:03 UTC, merged